### ISSUE TITLE
ItemResponse: NotSerializableException: scala.collection.immutable.MapLike

### ISSUE THREAD

**Issue by bavadim** [psgr/dev#1]
DTO объекты нормально не маршалятся. Пример эксепшена (то же самое должно быть и со стандартным механизмом маршалинга):

org.infinispan.persistence.spi.PersistenceException: org.infinispan.commons.marshall.NotSerializableException: scala.collection.immutable.MapLike$$anon$2
        at org.infinispan.marshall.core.MarshalledEntryImpl.marshall(MarshalledEntryImpl.java:107)
        at org.infinispan.marshall.core.MarshalledEntryImpl.getValueBytes(MarshalledEntryImpl.java:88)
        at org.infinispan.persistence.file.SingleFileStore.write(SingleFileStore.java:328)
        ... 55 more
Caused by: org.infinispan.commons.marshall.NotSerializableException: scala.collection.immutable.MapLike$$anon$2
Caused by: an exception which occurred:
        in field x
        in field images
        in field x
        in field details
        in field item
        in object psgr.protocol.market.response.ItemResponse@8eb02cef

**Comment by alari** [comment]
@bavadim
- не в тот проект тикет засунул
- для хранения нужно использовать не классы протокола, а внутреннее представление. протокол должен меняться независимо от эволюции бд
